/**
 * HTML email template for AI Trends Digest
 */

import type { ResearchResult } from './types'

/**
 * Generate HTML email from research results
 */
export function generateEmailHtml(
	results: ResearchResult[],
	weekDate: string,
): string {
	const sections = results.map(generateTopicSection).join('\n')
	const stats = generateStatsFooter(results)

	return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Trends Digest</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .container {
      background: white;
      border-radius: 8px;
      padding: 24px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    h1 {
      color: #1a1a1a;
      font-size: 24px;
      margin-bottom: 8px;
    }
    .subtitle {
      color: #666;
      font-size: 14px;
      margin-bottom: 24px;
    }
    h2 {
      color: #2563eb;
      font-size: 18px;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 8px;
      margin-top: 32px;
    }
    .highlight {
      background: #f0f9ff;
      border-left: 4px solid #2563eb;
      padding: 12px 16px;
      margin: 16px 0;
      border-radius: 0 4px 4px 0;
    }
    .source {
      background: #fafafa;
      border-radius: 6px;
      padding: 12px;
      margin: 8px 0;
    }
    .source-header {
      font-weight: 600;
      color: #1a1a1a;
      margin-bottom: 4px;
    }
    .source-meta {
      font-size: 12px;
      color: #666;
    }
    .engagement {
      display: inline-block;
      background: #e5e7eb;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 11px;
      margin-right: 4px;
    }
    .reddit { color: #ff4500; }
    .twitter { color: #1da1f2; }
    .web { color: #059669; }
    a {
      color: #2563eb;
      text-decoration: none;
    }
    a:hover {
      text-decoration: underline;
    }
    .footer {
      margin-top: 32px;
      padding-top: 16px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #666;
    }
    .stats {
      background: #f9fafb;
      padding: 16px;
      border-radius: 6px;
      margin-top: 24px;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      text-align: center;
    }
    .stat-value {
      font-size: 20px;
      font-weight: 700;
      color: #1a1a1a;
    }
    .stat-label {
      font-size: 11px;
      color: #666;
      text-transform: uppercase;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🤖 AI Trends Digest</h1>
    <p class="subtitle">Week of ${weekDate}</p>

    ${sections}

    ${stats}

    <div class="footer">
      <p>Generated by <a href="https://github.com/nathanvale/side-quest-plugins">SideQuest Research Plugin</a></p>
      <p>Data sourced from Reddit, X, and web searches over the last 30 days.</p>
    </div>
  </div>
</body>
</html>
`.trim()
}

function generateTopicSection(result: ResearchResult): string {
	const highlights: string[] = []

	// Reddit highlights
	if (result.reddit?.threads?.length) {
		const topThreads = result.reddit.threads.slice(0, 3)
		for (const thread of topThreads) {
			highlights.push(`
        <div class="source">
          <div class="source-header">
            <span class="reddit">r/${escapeHtml(thread.subreddit)}</span>
            <a href="${sanitizeUrl(thread.url)}">${escapeHtml(thread.title)}</a>
          </div>
          <div class="source-meta">
            <span class="engagement">↑ ${thread.upvotes}</span>
            <span class="engagement">💬 ${thread.comments}</span>
          </div>
          ${thread.snippet ? `<p style="margin: 8px 0 0 0; font-size: 13px; color: #555;">${escapeHtml(thread.snippet)}</p>` : ''}
        </div>
      `)
		}
	}

	// X highlights
	if (result.x?.posts?.length) {
		const topPosts = result.x.posts.slice(0, 3)
		for (const post of topPosts) {
			highlights.push(`
        <div class="source">
          <div class="source-header">
            <span class="twitter">@${escapeHtml(post.handle)}</span>
          </div>
          <p style="margin: 4px 0; font-size: 13px;">${escapeHtml(truncate(post.content, 200))}</p>
          <div class="source-meta">
            <span class="engagement">❤️ ${post.likes}</span>
            <span class="engagement">🔄 ${post.reposts}</span>
            <a href="${sanitizeUrl(post.url)}" style="font-size: 11px;">View post</a>
          </div>
        </div>
      `)
		}
	}

	// Web highlights
	if (result.web?.pages?.length) {
		const topPages = result.web.pages.slice(0, 2)
		for (const page of topPages) {
			highlights.push(`
        <div class="source">
          <div class="source-header">
            <span class="web">${escapeHtml(page.domain)}</span>
            <a href="${sanitizeUrl(page.url)}">${escapeHtml(truncate(page.title, 60))}</a>
          </div>
          ${page.snippet ? `<p style="margin: 4px 0 0 0; font-size: 13px; color: #555;">${escapeHtml(truncate(page.snippet, 150))}</p>` : ''}
        </div>
      `)
		}
	}

	return `
    <h2>${escapeHtml(result.topic)}</h2>
    ${highlights.length > 0 ? highlights.join('\n') : '<p style="color: #666;">No results found for this topic.</p>'}
  `
}

function generateStatsFooter(results: ResearchResult[]): string {
	let totalRedditThreads = 0
	let totalUpvotes = 0
	let totalXPosts = 0
	let totalLikes = 0
	let totalWebPages = 0

	for (const result of results) {
		if (result.reddit?.stats) {
			totalRedditThreads += result.reddit.stats.totalThreads
			totalUpvotes += result.reddit.stats.totalUpvotes
		}
		if (result.x?.stats) {
			totalXPosts += result.x.stats.totalPosts
			totalLikes += result.x.stats.totalLikes
		}
		if (result.web?.stats) {
			totalWebPages += result.web.stats.totalPages
		}
	}

	return `
    <div class="stats">
      <div class="stats-grid">
        <div>
          <div class="stat-value">${totalRedditThreads}</div>
          <div class="stat-label">Reddit Threads</div>
          <div style="font-size: 10px; color: #888;">${totalUpvotes.toLocaleString()} upvotes</div>
        </div>
        <div>
          <div class="stat-value">${totalXPosts}</div>
          <div class="stat-label">X Posts</div>
          <div style="font-size: 10px; color: #888;">${totalLikes.toLocaleString()} likes</div>
        </div>
        <div>
          <div class="stat-value">${totalWebPages}</div>
          <div class="stat-label">Web Pages</div>
        </div>
      </div>
    </div>
  `
}

/**
 * Generate plain text version of the email
 */
export function generateEmailText(
	results: ResearchResult[],
	weekDate: string,
): string {
	const sections = results.map(generateTopicTextSection).join('\n\n---\n\n')

	return `
AI TRENDS DIGEST
Week of ${weekDate}

${sections}

---

Generated by SideQuest Research Plugin
Data sourced from Reddit, X, and web searches over the last 30 days.
`.trim()
}

function generateTopicTextSection(result: ResearchResult): string {
	const lines: string[] = [`## ${result.topic}`, '']

	// Reddit
	if (result.reddit?.threads?.length) {
		lines.push('Reddit:')
		for (const thread of result.reddit.threads.slice(0, 3)) {
			lines.push(`  • r/${thread.subreddit}: ${thread.title}`)
			lines.push(`    ↑${thread.upvotes} 💬${thread.comments} - ${thread.url}`)
		}
		lines.push('')
	}

	// X
	if (result.x?.posts?.length) {
		lines.push('X/Twitter:')
		for (const post of result.x.posts.slice(0, 3)) {
			lines.push(`  • @${post.handle}: ${truncate(post.content, 100)}`)
			lines.push(`    ❤️${post.likes} 🔄${post.reposts} - ${post.url}`)
		}
		lines.push('')
	}

	// Web
	if (result.web?.pages?.length) {
		lines.push('Web:')
		for (const page of result.web.pages.slice(0, 2)) {
			lines.push(`  • ${page.domain}: ${page.title}`)
			lines.push(`    ${page.url}`)
		}
	}

	return lines.join('\n')
}

function escapeHtml(text: string): string {
	return text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&#039;')
}

function sanitizeUrl(url: string): string {
	try {
		const parsed = new URL(url)
		if (!['http:', 'https:'].includes(parsed.protocol)) {
			return '#'
		}
		return escapeHtml(url)
	} catch {
		return '#'
	}
}

function truncate(text: string, maxLength: number): string {
	if (text.length <= maxLength) return text
	return `${text.slice(0, maxLength - 3)}...`
}
